// qr-order-frontend/src/pages/OrderStatus.jsx
import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { api } from "/src/api";

export default function OrderStatus() {
  const { orderId } = useParams();
  const [data, setData] = useState(null);
  const [err, setErr] = useState("");

  useEffect(() => {
    let timer;

    async function load() {
      try {
        setErr("");
        const res = await api.get(`/api/orders/${orderId}`);
        setData(res.data);
      } catch (e) {
        setErr(e?.response?.data?.error || e.message);
      }
    }

    load();
    timer = setInterval(load, 3000);
    return () => clearInterval(timer);
  }, [orderId]);

  if (err) return <div style={{ padding: 16, color: "crimson" }}>Error: {err}</div>;
  if (!data) return <div style={{ padding: 16 }}>Loading...</div>;

  const { order, items } = data;

  return (
    <div style={{ padding: 16, fontFamily: "Arial", maxWidth: 700 }}>
      <h2>Order #{order.id}</h2>
      <div>Status: <b>{order.status}</b></div>
      <div style={{ marginTop: 6 }}>
        Total: <b>{Number(order.grand_total ?? order.total ?? 0).toLocaleString()} đ</b>
      </div>

      <h3 style={{ marginTop: 16 }}>Items</h3>
      <div style={{ display: "grid", gap: 10 }}>
        {items.map((it) => (
          <div key={it.id} style={{ border: "1px solid #eee", borderRadius: 8, padding: 10 }}>
            <div style={{ fontWeight: 700 }}>{it.name}</div>
            <div>Qty: {it.quantity}</div>
            {it.note ? <div>Note: {it.note}</div> : null}
          </div>
        ))}
      </div>

      <div style={{ marginTop: 16, color: "#555" }}>
        (Trang này tự refresh mỗi 3 giây để cập nhật trạng thái.)
      </div>
    </div>
  );
}

// qr-order-frontend/src/pages/OrderStatus.vue
<template>
  <div>
    <h1>Order {{ orderId }}</h1>

    <div v-if="loading">Loading...</div>

    <div v-if="!loading && order">
      <p>Status: {{ order.status }}</p>
      <p>Total: {{ order.grand_total }}</p>

      <h3>Items</h3>

      <div v-for="item in items" :key="item.id" class="order-item">
        <p>{{ item.name }} x {{ item.quantity }}</p>
        <p>{{ item.line_total }} VND</p>
      </div>
    </div>
  </div>
</template>

<script>
import { api } from "../api/api"
import { useRoute } from "vue-router"

export default {

  setup() {
    const route = useRoute()
    const orderId = route.params.orderId
    return { orderId }
  },

  data() {
    return {
      order: null,
      items: [],
      loading: true
    }
  },

  mounted() {
    this.fetchOrder()

    // auto refresh mỗi 5 giây
    setInterval(() => {
      this.fetchOrder()
    }, 5000)
  },

  methods: {

    async fetchOrder() {

      try {

        const res = await api.get(`/orders/${this.orderId}`)

        this.order = res.data.order
        this.items = res.data.items

        this.loading = false

      } catch (err) {

        console.error(err)

      }

    }

  }

}
</script>

<style>
.order-item {
  border: 1px solid #ccc;
  padding: 10px;
  margin-bottom: 10px;
}
</style>
